---
- name: Reset error code
  set_fact:
    dci_cvp_error_detected: false

- block:
    # Operator subscribe
    - name: "Run operator subscribe step"
      include_role:
        name: "{{ dci_cvp_cache_dir }}/cvp_operator_repo/roles/optional-operators-subscribe"
      vars:
        kubeconfig_path: "{{ dci_cvp_kubeconfig }}"

  rescue:
    - name: Set error detected
      set_fact:
        dci_cvp_error_detected: true

  always:
    # Collect pull events
    - name: "Parse the collected image pull events"
      include_role:
        name: "{{ dci_cvp_cache_dir }}/cvp_operator_repo/roles/collect_modified_images"
      vars:
        events_file_path: "{{ dci_cvp_logs }}/image_pull_events.json"
        work_dir: "{{ dci_cvp_logs }}"
        kubeconfig_path: "{{ dci_cvp_kubeconfig }}"

# scorecard...
- name: "Run Scorecard tests for operator bundle"
  include_role:
    name: "{{ dci_cvp_cache_dir }}/cvp_operator_repo/roles/operator_bundle_scorecard_tests"
  vars:
    OPENSHIFT_AUTH: "{{ dci_cvp_pullsecret_file }}"
    kubeconfig_path: "{{ dci_cvp_kubeconfig }}"
  when: not dci_cvp_error_detected

- name: Fail if error detected
  fail:
    msg: "Failure running cvp_operator roles"
  when: dci_cvp_error_detected
...
